# Generated by Django 4.2 on 2023-04-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poesia',
            fields=[
                ('id_poesia', models.AutoField(primary_key=True, serialize=False)),
                ('title_poesia', models.CharField(max_length=50)),
                ('author_poesia', models.CharField(max_length=50)),
                ('descr_poesia', models.CharField(max_length=1000)),
                ('user_poesia', models.CharField(max_length=50)),
                ('creationdate_poesia', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImgPoesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_poesia', models.ImageField(blank=True, null=True, upload_to='poesia')),
                ('id_poesia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClubArte.poesia')),
            ],
        ),
    ]
