# Generated by Django 4.2 on 2023-04-06 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubArte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id_movie', models.AutoField(primary_key=True, serialize=False)),
                ('title_movie', models.CharField(max_length=50)),
                ('direc_movie', models.CharField(max_length=50)),
                ('descr_movie', models.CharField(max_length=1000)),
                ('user_movie', models.CharField(max_length=50)),
                ('creationdate_movie', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImgCine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_movie', models.ImageField(blank=True, null=True, upload_to='cine')),
                ('id_movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClubArte.cine')),
            ],
        ),
    ]
