# Generated by Django 4.2 on 2023-04-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubArte', '0002_cine_imgcine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('title_foto', models.CharField(max_length=50)),
                ('author_foto', models.CharField(max_length=60)),
                ('descr_foto', models.CharField(max_length=1000)),
                ('user_foto', models.CharField(max_length=50)),
                ('creationdate_foto', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImgFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_foto', models.ImageField(blank=True, null=True, upload_to='fotog')),
                ('id_foto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClubArte.fotografia')),
            ],
        ),
    ]
